name: Copy Doing.html to GitHub Pages Repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Doing repo
        uses: actions/checkout@v3

      - name: Clone GitHub Pages repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          git clone https://x-access-token:${{ secrets.GH_PAGES_TOKEN }}@github.com/YChiasma/YChiasma.github.io.git gh-pages
          
      - name: Copy Doing.html
        run: |
          cp Doing.html gh-pages/Doing.html
          cd gh-pages
          git add Doing.html
          git commit -m "Update Doing.html from Doing repo [skip ci]" || echo "No changes to commit"
          git push
